"""add campo de data ao post

Revision ID: 885f62139a50
Revises: ece8cdb29f20
Create Date: 2022-01-20 21:00:59.031259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885f62139a50'
down_revision = 'ece8cdb29f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_column('post', 'timestamp')
    # ### end Alembic commands ###
