"""create table post

Revision ID: b15af6f084a7
Revises: 00d13b3c656f
Create Date: 2022-01-18 12:50:32.294412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b15af6f084a7'
down_revision = '00d13b3c656f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=180), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_message'), 'posts', ['message'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_message'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
